#!/usr/bin/env ruby
require 'ansi/code'
require 'io/console'
begin
  $:.unshift File.expand_path(File.dirname(__FILE__) + "/../lib")
  require 'universa'
rescue LoadError => e
  require 'universa'
end

require 'universa/tools'
require 'universa/keytool/keytool'

